# 服务器配置
server:
  # 基本配置
  name: "nova" # 服务器应用名称
  host: "0.0.0.0" # 服务器IP
  port: 7777 # 服务器监听端口
  maxConn: 100000 # 允许的客户端连接最大数量
  workerPoolSize: 1000000 # 工作任务池最大工作Goroutine数量
  # 系统日志配置
  access:
    level: "debug" # 日志打印级别 debug、info、warn、error、dpanic、panic、fatal
    ctxKeys: ["RequestId"] # 自定义Context上下文变量名称，自动打印Context的变量到日志中。默认为空
    format: "json" # 输出日志格式 logfmt、json
    path: "logs/sys" # 输出日志文件路径
    filename: "access-%Y-%m-%d.log" # 输出日志文件名称
    maxSize: 10 # 单个日志文件最多存储量，单位(mb)
    maxBackups: 10 # 日志备份文件最多数量
    maxAge: 7 # 日志保留时间，单位:天(day)
    compress: false # 是否压缩日志
    stdout: true # 是否输出到控制台
  error:
    level: "error" # 日志打印级别 debug、info、warn、error、dpanic、panic、fatal
    ctxKeys: ["RequestId"] # 自定义Context上下文变量名称，自动打印Context的变量到日志中。默认为空
    format: "json" # 输出日志格式 logfmt、json
    path: "logs/sys" # 输出日志文件路径
    filename: "error-%Y-%m-%d.log" # 输出日志文件名称
    maxSize: 10 # 单个日志文件最多存储量，单位(mb)
    maxBackups: 10 # 日志备份文件最多数量
    maxAge: 7 # 日志保留时间，单位:天(day)
    compress: false # 是否压缩日志
    stdout: true # 是否输出到控制台

# 日志配置
logger:
  access:
    level: "debug" # 日志打印级别 debug、info、warn、error、dpanic、panic、fatal
    ctxKeys: ["RequestId"] # 自定义Context上下文变量名称，自动打印Context的变量到日志中。默认为空
    format: "json" # 输出日志格式 logfmt、json
    path: "logs/server" # 输出日志文件路径
    filename: "access-%Y-%m-%d.log" # 输出日志文件名称
    maxSize: 10 # 单个日志文件最多存储量，单位(mb)
    maxBackups: 10 # 日志备份文件最多数量
    maxAge: 7 # 日志保留时间，单位:天(day)
    compress: false # 是否压缩日志
    stdout: true # 是否输出到控制台
  error:
    level: "error" # 日志打印级别 debug、info、warn、error、dpanic、panic、fatal
    ctxKeys: ["RequestId"] # 自定义Context上下文变量名称，自动打印Context的变量到日志中。默认为空
    format: "json" # 输出日志格式 logfmt、json
    path: "logs/server" # 输出日志文件路径
    filename: "error-%Y-%m-%d.log" # 输出日志文件名称
    maxSize: 10 # 单个日志文件最多存储量，单位(mb)
    maxBackups: 10 # 日志备份文件最多数量
    maxAge: 7 # 日志保留时间，单位:天(day)
    compress: false # 是否压缩日志
    stdout: true # 是否输出到控制台
