# 服务器配置
server:
  name: "Nova" # 服务器应用名称
  host: "0.0.0.0" # 服务器IP
  port: 9999 # 服务器监听端口（uint16）
  maxConn: 10000 # 允许的客户端连接最大数量（uint32）
  workerPoolSize: 100000 # 工作任务池最大工作Goroutine数量（uint32）
  packageHeaderLen: 8 # 包头的长度（字节 uint8）
  maxPacketSize: 4096 # 数据包的最大值（字节 uint32）
  maxMsgChanLen: 1024 # SendBuffMsg发送消息的缓冲最大长度（字节 uint32）

# 日志配置
logger:
  - level: "debug" # 日志打印级别 debug、info、warn、error、dpanic、panic、fatal
    format: "json" # 输出日志格式 logfmt、json
    path: "logs" # 输出日志文件路径
    filename: "info.log" # 输出日志文件名称
    maxSize: 10 # 单个日志文件最多存储量，单位(mb)
    maxBackups: 10 # 日志备份文件最多数量
    maxAge: 7 # 日志保留时间，单位:天(day)
    compress: false # 是否压缩日志
    stdout: true # 是否输出到控制台
  - level: "error" # 日志打印级别 debug、info、warn、error、dpanic、panic、fatal
    format: "json" # 输出日志格式 logfmt、json
    path: "logs" # 输出日志文件路径
    filename: "error.log" # 输出日志文件名称
    maxSize: 10 # 单个日志文件最多存储量，单位(mb)
    maxBackups: 10 # 日志备份文件最多数量
    maxAge: 7 # 日志保留时间，单位:天(day)
    compress: false # 是否压缩日志
    stdout: true # 是否输出到控制台
