# 服务器配置
server:
  name: "Nova" # 服务器应用名称，默认"Nova"
  port: 8888 # 服务器监听端口（uint16）
  heartbeatMax: 5000 # 最长心跳检测间隔时间（单位: 毫秒 time.Duration），默认 5000
  maxConn: 3 # 允许的客户端连接最大数量，默认 3（uint32）
  workerPoolSize: 10 # 工作任务池最大工作 Goroutine 数量，默认 10（uint32）
  maxWorkerTaskLen: 1024 # 工作任务池 Worker 对应负责的任务队列最大任务存储数量，默认 1024（uint32）
  maxPacketSize: 4096 # 数据包的最大值，默认 4096（单位:字节 uint32）
  packetMethod: 1 # 封包和拆包方式，默认 1，1: 消息ID(4字节)-消息体长度(4字节)-消息内容（单位:字节 uint8）
  endian: 1 # 字节存储次序，默认小端，1: 小端 2: 大端（单位:字节 uint8）
  maxMsgChanLen: 1024 # SendBuffMsg发送消息的缓冲最大长度，默认 1024（单位:字节 uint32）

# 日志配置
logger:
  - level: "debug" # 日志打印级别 debug、info、warn、error、dpanic、panic、fatal
    format: "json" # 输出日志格式 logfmt、json
    path: "logs" # 输出日志文件路径
    filename: "info.log" # 输出日志文件名称
    maxSize: 10 # 单个日志文件最多存储量（单位:MB int）
    maxBackups: 10 # 日志备份文件最多数量（int）
    maxAge: 7 # 日志保留时间（单位:天 int）
    compress: false # 是否压缩日志
    stdout: true # 是否输出到控制台
  - level: "error" # 日志打印级别 debug、info、warn、error、dpanic、panic、fatal
    format: "json" # 输出日志格式 logfmt、json
    path: "logs" # 输出日志文件路径
    filename: "error.log" # 输出日志文件名称
    maxSize: 10 # 单个日志文件最多存储量（单位:MB int）
    maxBackups: 10 # 日志备份文件最多数量（int）
    maxAge: 7 # 日志保留时间（单位:天 int）
    compress: false # 是否压缩日志
    stdout: true # 是否输出到控制台
