# 服务器配置
server:
  name: "Nova" # 服务器应用名称，默认"Nova"
  network: "tcp" # 服务器网络协议 tcp、tcp4、tcp6、udp、udp4、udp6、unix
  port: 8099 # 服务器监听端口
  heartBeat: "10s" # 心跳发送间隔时间（一定要小于 maxHeartBeat 配置），默认 10秒
  maxHeartBeat: "15s" # 最长心跳检测间隔时间（一定要大于 heartBeat 配置），默认 15秒
  maxConn: 3 # 允许的客户端连接最大数量，默认 3
  workerPoolSize: 10 # 工作任务池最大工作 Goroutine 数量，默认 10
  workerPoolSizeOverflow: 5 # 当处理任务超过工作任务池的容量时，增加的 Goroutine 数量，默认 5
  maxPacketSize: 4096 # 数据包的最大值（单位:字节），默认 4096
  packetMethod: 1 # 封包和拆包方式，1: 消息ID(2字节)-消息体长度(4字节)-消息内容，默认 1
  endian: 1 # 字节存储次序，1: 小端 2: 大端，默认 1
  slowThreshold: "200ms" # 处理请求或执行操作时的慢速阈值

# 日志配置
logger:
  path: "logs" # 输出日志文件路径
  details:
    - type: 1 # 日志类型 0:打印所有级别 1:打印 DEBUG、INFO 级别 2:打印 WARN、ERROR、DPANIC、PANIC、FATAL 级别，默认0
      level: 0 # 日志打印级别 0:DEBUG 1:INFO 2:WARN 3:ERROR 4:DPANIC、5:PANIC、6:FATAL，默认0
      format: 1 # 输出日志格式 0:logfmt 1:json，默认1
      filename: "info.log" # 输出日志文件名称
      maxSize: 10 # 单个日志文件最多存储量（单位:MB）
      maxBackups: 10 # 日志备份文件最多数量
      maxAge: 7 # 日志保留时间（单位:天）
      compress: false # 是否压缩日志
      stdout: true # 是否输出到控制台
    - type: 2 # 日志类型 0:打印所有级别 1:打印 DEBUG、INFO 级别 2:打印 WARN、ERROR、DPANIC、PANIC、FATAL 级别，默认0
      level: 2 # 日志打印级别 0:DEBUG 1:INFO 2:WARN 3:ERROR 4:DPANIC、5:PANIC、6:FATAL，默认0
      format: 1 # 输出日志格式 0:logfmt 1:json，默认1
      filename: "error.log" # 输出日志文件名称
      maxSize: 10 # 单个日志文件最多存储量（单位:MB）
      maxBackups: 10 # 日志备份文件最多数量
      maxAge: 7 # 日志保留时间（单位:天）
      compress: false # 是否压缩日志
      stdout: true # 是否输出到控制台
