# 单元测试用
# 日志配置
logger:
  - level: "debug" # 日志打印级别 debug、info、warn、error、dpanic、panic、fatal
    format: "json" # 输出日志格式 logfmt、json
    path: "logs" # 输出日志文件路径
    filename: "info.log" # 输出日志文件名称
    maxSize: 10 # 单个日志文件最多存储量，单位(mb)
    maxBackups: 10 # 日志备份文件最多数量
    maxAge: 7 # 日志保留时间，单位:天(day)
    compress: false # 是否压缩日志
    stdout: true # 是否输出到控制台
  - level: "error" # 日志打印级别 debug、info、warn、error、dpanic、panic、fatal
    format: "json" # 输出日志格式 logfmt、json
    path: "logs" # 输出日志文件路径
    filename: "error.log" # 输出日志文件名称
    maxSize: 10 # 单个日志文件最多存储量，单位(mb)
    maxBackups: 10 # 日志备份文件最多数量
    maxAge: 7 # 日志保留时间，单位:天(day)
    compress: false # 是否压缩日志
    stdout: true # 是否输出到控制台
